image: Ubuntu1804  # образ для сборки

stack: node 10  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - lscpu  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - nvidia-smi   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования
